
# function for sum 



def additoin(x, y):
    x = 10
    y = 20
    print("Addition:", x + b)

#_______________________________________


#_______________________________________

#type of exception

try:
    additoin(20,"h")
except NameError:
    print("operation fails")
else:
    print("the operation is successful")